services:
  - type: web
    name: canvas-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: CANVAS_URL
        sync: false
      - key: CANVAS_TOKEN
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false 
